[package]
name = "snmpmock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rasn = "0.12.0"
rasn-smi = "0.12.0"
rasn-snmp = "0.12.0"
thiserror = "1.0.50"
